apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1
  version: "1.33"
  tags:
    owner: KastroKiran
    bu: kkv
    environment: prod
    project: efk-logging

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

iam:
  withOIDC: true

managedNodeGroups:
  - name: Worker-Node-Group
    instanceType: t3.large
    minSize: 3
    maxSize: 5
    privateNetworking: true
    volumeSize: 20
    # ssh:
    #   allow: true
      #publicKeyName: new-keypair
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: false
        certManager: false
        ebs: true
        fsx: false
        efs: false
        albIngress: true
        xRay: false
        cloudWatch: false
    labels:
      lifecycle: ec2-autoscaler
